# Generated by Django 3.0.8 on 2021-10-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=25)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'db_table': 'tp_cargo',
            },
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_categoria', models.CharField(max_length=25)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'tp_categoria',
            },
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=25)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'tp_ciudad',
            },
        ),
        migrations.CreateModel(
            name='detalle_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Detalle_factura',
                'verbose_name_plural': 'Detalle_factura',
                'db_table': 'tp_detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='detalle_mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_mantenimiento', models.CharField(max_length=200)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Detalle_mantenimiento',
                'verbose_name_plural': 'Detalle_mantenimientos',
                'db_table': 'tp_detalle_mantenimineto',
            },
        ),
        migrations.CreateModel(
            name='devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('fecha_devolucion', models.DateTimeField()),
                ('cantidad', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devolucion',
                'db_table': 'tp_devolucion',
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'tp_empleado',
            },
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipo',
                'db_table': 'tp_equipo',
            },
        ),
        migrations.CreateModel(
            name='forma_de_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_forma_de_pago', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Forma_de_pago',
                'verbose_name_plural': 'Forma_de_pagos',
                'db_table': 'tp_forma_de_pago',
            },
        ),
        migrations.CreateModel(
            name='mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField()),
                ('observacion_retiro', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField()),
                ('observacion_entrega', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimiento',
                'db_table': 'tp_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'tp_producto',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_servicios', models.CharField(max_length=100)),
                ('precios', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicio',
                'db_table': 'tp_servicio',
            },
        ),
        migrations.CreateModel(
            name='tipo_de_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=25)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tipo_De_Documento',
                'verbose_name_plural': 'Tipo_De_Documentos',
                'db_table': 'tp_tipo_de_documento',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('Ciudad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Fast_All_Solutions.ciudad')),
            ],
            options={
                'db_table': 'tp_proveedor',
            },
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_facturacion', models.DateTimeField()),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=7)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('producto_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Fast_All_Solutions.producto')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Factura',
                'db_table': 'tp_factura',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('Tipo_Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Fast_All_Solutions.tipo_de_documento')),
                ('ciudad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Fast_All_Solutions.ciudad')),
            ],
            options={
                'db_table': 'tp_cliente',
            },
        ),
    ]
