# Generated by Django 3.0.8 on 2021-10-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Fast_All_Solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='producto_v',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='Sistema_Fast_All_Solutions.producto'),
        ),
    ]
